# This is a basic workflow to help you get started with Actions
CODE partikular JAPAN blue
SANDRA–KANANG LETTAU GERMANY 25.04.1988    ROLAND LETTAU 0 SAOWANEE NAKSUWAN 
32429 MINDEN 
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
ORBITAL NASA univers 
  push: 
    branches: chemical 
  pull_request:
    branches:  METAPHYSIK

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: ===  NEXT life ASTRONAUT, HUMANS RIGHT  GENERALSSEKRETÄR 
  # This workflow contains a single job called "build"
  build: BIOCULAR 
    # The type of runner that the job will run on
    Never!!!!IN THE SAME vektor with MARTIN father from MAX–RALF 
      FREQUENZ CHRISTALL BELLS 
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps: HORIZONTAL
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: BREATH

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |IS ANYBODY THERE TO LOVE ME 
        echo Add other actions to build,
        echo test, and deploy your project.
